### PR TITLE
Add GH Actions

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by dmcgowan** [comment]
I might separate the addition of Github actions from the removal of Travis. Since this PR is showing neither running. I'm not sure if other opencontainers projects have moved to actions

**Comment by thaJeztah** [comment]
> I might separate the addition of Github actions from the removal of Travis

sure, can do

> I'm not sure if other opencontainers projects have moved to actions

Not many yet. I see https://github.com/opencontainers/oci-conformance uses GitHub Actions

**Comment by thaJeztah** [comment]
Restored the travis YAML in this PR, and pushed https://github.com/opencontainers/go-digest/pull/59 as a draft

**Review by AkihiroSuda — APPROVED** [review]

**Comment by caniszczyk** [comment]
+1 to moving off of Travis CI

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
