### PR TITLE
*: add LICENSE headers to Go files

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
PTAL @opencontainers/go-digest-maintainers

**Comment by dmcgowan** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Comment by stevvooe** [comment]
@caniszczyk Do @aaronlehmann and @dmcgowan need to be added to pullapprove?

**Comment by caniszczyk** [comment]
@stevvooe I just kicked PullApprove to sync the team, should be good moving forward, looks like PA didn't pick them up when they were voted on to the @opencontainers/go-digest-maintainers team. So I'd ask @aaronlehmann and @dmcgowan to try doing the LGTM again.

**Comment by dmcgowan** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
