### PR TITLE
README: update project urls for badges et al.

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by caniszczyk** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM >-winces-<

**Comment by stevvooe** [comment]
@caniszczyk O weird. Looks like you're not on the reviewer list...

Let's try this out: @opencontainers/go-digest-maintainers

**Comment by caniszczyk** [comment]
@stevvooe technically I shouldn't be an official MAINTAINER, so this is on purpose :)

**Comment by wking** [comment]
On Thu, Jan 05, 2017 at 04:51:15PM -0800, Stephen Day wrote:
> @caniszczyk O weird. Looks like you're not on the reviewer list...

That's appropriate, no?  He's not in [1] either.

[1]: https://github.com/opencontainers/go-digest/blob/a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb/MAINTAINERS

**Comment by vbatts** [comment]
i'm guessing some of the other s/docker/opencontainers/g things will happen later? like the respond to security@docker.com?

**Comment by stevvooe** [comment]
@vbatts Yes, I'm trying to keep these focused so we can get the updates in quickly.

**Comment by wking** [comment]
On Mon, Jan 09, 2017 at 07:56:19PM -0800, Vincent Batts wrote:
> … like the respond to security@docker.com?

This is in flight with #20.

**Comment by jonboulle** [comment]
lgtm

**Comment by caniszczyk** [comment]
Hey @vbatts, can you sign off on this one ;)?

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
