### PR TITLE
Add digestset subpackage

### PR DESCRIPTION
**Pull request by dmcgowan**
Adds digestset from https://github.com/docker/distribution/tree/master/digestset

Originally the digest set was a part of the `digest` package, but was split out to make the `go-digest` package smaller when it moved from `docker/distribution` to here. This package has remained stable and used in situations when a "short" digest needs to be resolved securely and unambiguously. This package is useful alongside `go-digest` but can be safely broken out into a separate package, without bloating importers who do not intend to use it.

This is helpful to address some `docker/distribution` vendoring issues for importers who only need this package (such as `containerd/containerd`).

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
LGTM

**Comment by thaJeztah** [comment]
Thanks! Looks like after this is merged, we need to do one more vendor round (containerd/cri and back)

**Comment by dmcgowan** [comment]
I propose we tag 1.0 after getting this merged in. Then vendoring changes can use the tag.

**Comment by Toasterson** [comment]
+1 from me for the 1.0 tag that makes modules behave a little better.

**Comment by stevvooe** [comment]
Looks like I've been removed from @opencontainers/go-digest-maintainers for some reason, so its not tracking my LGTM.

**Comment by caniszczyk** [comment]
added @stevvooe back and resync'd PullApprove, his next LGTM should be picked up

**Pull request merged**
