### PR TITLE
MAINTAINERS: fix jonboulle's email

### LINKED ISSUE #43: MAINTAINERS update needed
@jonboulle email incorrect in MAINTAINERS, see https://github.com/opencontainers/image-spec/blob/master/MAINTAINERS for current email

### PR DESCRIPTION
**Pull request by jonboulle**
Fixes #43

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dmcgowan @stevvooe

**Comment by dmcgowan** [comment]
LGTM

**Comment by caniszczyk** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
merge?

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
