### PR TITLE
Remove travis.yml

### PR DESCRIPTION
**Pull request by thaJeztah**
follow-up to https://github.com/opencontainers/go-digest/pull/58

### CODE REVIEW

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
rebased, because https://github.com/opencontainers/go-digest/pull/58 was merged; GH actions are now running here

**Review by AkihiroSuda — APPROVED** [review]

**Comment by thaJeztah** [comment]
@dmcgowan @AkihiroSuda PTAL

**Comment by thaJeztah** [comment]
🤦 Akihiro already reviewed; sorry for the ping

**Review by dmcgowan — APPROVED** [review]
LGTM

**Pull request merged**
