### PR TITLE
Add CODEOWNERS, remove .pullapprove.yml

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
What's the context?

**Comment by dmcgowan** [comment]
I assume to get rid of pullapprove. What does CODEOWNERS file add over just replacing pullapprove with github's threshold approve?

**Comment by stevvooe** [comment]
Doesn't CODEOWNERS drive github's feature?

**Review by stevvooe — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I don't think the CODEOWNERS is strictly needed to make the feature work; configuring "number of approvals" should probably be enough. That said, CODEOWNERS will allow automatically request a review from those listed.

Not sure though if "Require review from Code Owners" will force _all_ code owners to leave a review (I guess we only need two out of that list)

Screenshot 2021-11-11 at 19 54 49

**Review by vbatts — APPROVED** [review]
it must be configured in the repo settings.
But LGTM for once we get that done (cc @caniszczyk )

**Review by dmcgowan — APPROVED** [review]

**Comment by caniszczyk** [comment]
LGTM (enabled the "Require a pull request before merging") setting

**Pull request merged**
